spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:25433/foo_db
    username: foo_user
    password: something
    max-active: 5
    max-idle: 5
    min-idle: 0
    initial-size: 0
    jmx-enabled: true
    test-on-borrow: true
    validation-query: select 1

server:
  port: -1

log:
  path:
    all:
      name: app.log
      dir:
        current: tmp/log
        history: tmp/log/history
      histsize: 2
    error:
      name: error.log
      dir:
        current: tmp/log
        history: tmp/log/history
      histsize: 2
  level:
    app: DEBUG
    root: INFO

application:
  kinesis:
    order:
      stream-name: kinesis-commerce-system-sample-order-stream
      application-name: kinesis-commerce-system-sample-order-consumer-v1
      region-name: ap-northeast-1
      idle-time-between-reads-in-millis: 1000
    purchase:
      stream-name: kinesis-commerce-system-sample-purchase-stream
      application-name: kinesis-commerce-system-sample-purchase-consumer-v1
      region-name: ap-northeast-1
      idle-time-between-reads-in-millis: 1000
    inventory:
      stream-name: kinesis-commerce-system-sample-inventory-stream
      application-name: kinesis-commerce-system-sample-inventory-consumer-v1
      region-name: ap-northeast-1
      idle-time-between-reads-in-millis: 1000

